source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'RealmSubqueryHelperExample' do
    pod 'Realm'
end

target 'RealmSubqueryHelperExampleTests' do
    pod 'Realm/Headers'
end